### ISSUE TITLE
How to runing this project ?

### ISSUE THREAD

**Issue by hoangnamitc** [avbdr/tinymvc-php#1]
How to configs for project runing ?

**Comment by avbdr** [comment]
are you running it under nginx or apache? 

under apache you need to have mod_rewrite enabled

under nginx you hneed something like that
```
server {
        listen 80 default_server;
        root /var/www/html/;

        index index.php;

        location / {
	        try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
            include /etc/nginx/snippets/fastcgi-php.conf;
            fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
        }
}
```

**Comment by hoangnamitc** [comment]
I config in file index.php.
runing in xampp but it only view 404 😞

**Comment by avbdr** [comment]
Show your index.php

**Comment by hoangnamitc** [comment]
I clone your repo and not edit any.
I'm only enter info connect db in array db.

**Comment by avbdr** [comment]
try https://www.phpflow.com/php/how-to-enable-mod_rewrite-module-in-apache/

**Comment by hoangnamitc** [comment]
i'm enabled mod_rewrite. but not working.

![image](https://user-images.githubusercontent.com/7042462/51075669-80fbde00-16c1-11e9-87ca-e21dd1e1d25e.png)

![image](https://user-images.githubusercontent.com/7042462/51075672-86592880-16c1-11e9-9b5b-01669a0c2971.png)

**Comment by avbdr** [comment]
You need to host tinymvc in the root, not in the subfolder.

Or create an alias tinymvc-php/index to root/index

**Comment by hoangnamitc** [comment]
it is working after me move outside root directory.
Thanks Bro support me!
